/* L402sdk FFI — auto-generated by cbindgen. Do not edit. */

#ifndef BOLT402_H
#define BOLT402_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an L402 client.
 */
typedef struct L402Client L402Client;

/**
 * Opaque handle to a mock L402 server.
 */
typedef struct L402MockServer L402MockServer;

/**
 * Opaque handle to an L402 response.
 */
typedef struct L402Response L402Response;

/**
 * Endpoint configuration for the mock server (path + price in sats).
 */
typedef struct L402Endpoint {
  /**
   * Null-terminated endpoint path (e.g. "/api/data").
   */
  const char *path;
  /**
   * Price in satoshis.
   */
  uint64_t price_sats;
} L402Endpoint;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message, or null if no error occurred.
 *
 * The returned string is valid until the next FFI call on the same thread.
 * Do **not** free it with `l402_string_free`.
 */
const char *l402_last_error_message(void);

/**
 * Free a string allocated by L402sdk FFI functions.
 *
 * # Safety
 *
 * `s` must be a pointer returned by a L402sdk FFI function, or null.
 */
void l402_string_free(char *s);

/**
 * Create a new mock L402 server with the given endpoints.
 *
 * Returns null on error (check `l402_last_error_message`).
 *
 * # Safety
 *
 * `endpoints` must point to `count` valid `L402Endpoint` structs.
 * Each `path` field must be a valid null-terminated C string.
 */
struct L402MockServer *l402_mock_server_new(const struct L402Endpoint *endpoints, uintptr_t count);

/**
 * Get the URL of the mock server.
 *
 * The returned string is owned by the server and valid until the server is freed.
 * Do **not** free it with `l402_string_free`.
 *
 * # Safety
 *
 * `server` must be a valid pointer from `l402_mock_server_new`.
 */
const char *l402_mock_server_url(const struct L402MockServer *server);

/**
 * Free a mock server.
 *
 * # Safety
 *
 * `server` must be a pointer from `l402_mock_server_new`, or null.
 */
void l402_mock_server_free(struct L402MockServer *server);

/**
 * Create a client connected to a mock server.
 *
 * The mock server must have been created with `l402_mock_server_new`.
 * Returns null on error.
 *
 * # Safety
 *
 * `server` must be a valid pointer from `l402_mock_server_new`.
 */
struct L402Client *l402_client_new_mock(const struct L402MockServer *server, uint64_t max_fee_sats);

/**
 * Free a client.
 *
 * # Safety
 *
 * `client` must be a pointer from `l402_client_new_mock`, or null.
 */
void l402_client_free(struct L402Client *client);

/**
 * Send a GET request through the L402 client.
 *
 * Returns null on error (check `l402_last_error_message`).
 *
 * # Safety
 *
 * `client` must be a valid client pointer. `url` must be a valid C string.
 */
struct L402Response *l402_client_get(struct L402Client *client, const char *url);

/**
 * Send a POST request through the L402 client.
 *
 * `body` may be null for requests with no body.
 * Returns null on error (check `l402_last_error_message`).
 *
 * # Safety
 *
 * `client` must be a valid client pointer. `url` must be a valid C string.
 * `body` must be a valid C string or null.
 */
struct L402Response *l402_client_post(struct L402Client *client, const char *url, const char *body);

/**
 * Get the HTTP status code from a response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint16_t l402_response_status(const struct L402Response *response);

/**
 * Check whether a Lightning payment was made for this response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
bool l402_response_paid(const struct L402Response *response);

/**
 * Get the response body as a C string.
 *
 * The returned string is owned by the response. Do not free it separately.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *l402_response_body(const struct L402Response *response);

/**
 * Check whether the response contains a payment receipt.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
bool l402_response_has_receipt(const struct L402Response *response);

/**
 * Get the amount paid in satoshis (0 if no receipt).
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint64_t l402_response_receipt_amount_sats(const struct L402Response *response);

/**
 * Get the routing fee in satoshis (0 if no receipt).
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint64_t l402_response_receipt_fee_sats(const struct L402Response *response);

/**
 * Get the payment hash from the receipt.
 *
 * Returns null if no receipt. The string is owned by the response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *l402_response_receipt_payment_hash(const struct L402Response *response);

/**
 * Get the preimage (proof of payment) from the receipt.
 *
 * Returns null if no receipt. The string is owned by the response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *l402_response_receipt_preimage(const struct L402Response *response);

/**
 * Free a response.
 *
 * # Safety
 *
 * `response` must be a pointer from `l402_client_get` or `l402_client_post`, or null.
 */
void l402_response_free(struct L402Response *response);

/**
 * Get the total amount spent by the client in satoshis.
 *
 * # Safety
 *
 * `client` must be a valid client pointer.
 */
uint64_t l402_client_total_spent(const struct L402Client *client);

/**
 * Get all receipts as a JSON array string.
 *
 * The caller must free the returned string with `l402_string_free`.
 * Returns null on error.
 *
 * # Safety
 *
 * `client` must be a valid client pointer.
 */
char *l402_client_receipts_json(const struct L402Client *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BOLT402_H */
