//! # bolt402-cln
//!
//! Core Lightning (CLN) gRPC backend adapter for the bolt402 L402 client SDK.
//!
//! This crate implements the [`bolt402_core::LnBackend`] trait using
//! CLN's gRPC API, enabling the L402 client to pay invoices, query balances,
//! and retrieve node information through a connected CLN node.
//!
//! ## Setup
//!
//! Connecting to CLN requires mTLS (mutual TLS) authentication:
//! - gRPC endpoint (e.g. `https://localhost:9736`)
//! - CA certificate (`ca.pem`)
//! - Client certificate (`client.pem`)
//! - Client private key (`client-key.pem`)
//!
//! These files are generated by CLN in `~/.lightning/<network>/`.
//!
//! ## Example
//!
//! ```rust,no_run
//! use bolt402_cln::ClnBackend;
//! use bolt402_core::LnBackend;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let backend = ClnBackend::connect(
//!     "https://localhost:9736",
//!     "/path/to/ca.pem",
//!     "/path/to/client.pem",
//!     "/path/to/client-key.pem",
//! ).await?;
//!
//! let info = backend.get_info().await?;
//! println!("Connected to: {} ({})", info.alias, info.pubkey);
//! # Ok(())
//! # }
//! ```
//!
//! ## Environment Variables
//!
//! You can also configure via environment variables:
//!
//! ```rust,no_run
//! use bolt402_cln::ClnBackend;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! // Reads CLN_GRPC_HOST, CLN_CA_CERT_PATH, CLN_CLIENT_CERT_PATH, CLN_CLIENT_KEY_PATH
//! let backend = ClnBackend::from_env().await?;
//! # Ok(())
//! # }
//! ```
//!
//! ## Architecture
//!
//! This crate is an adapter in the hexagonal architecture. It depends on
//! `bolt402-core` for the [`bolt402_core::LnBackend`] port trait and uses
//! `tonic` with vendored CLN proto files for gRPC communication.

#![warn(missing_docs)]

mod backend;
mod error;

/// Generated CLN gRPC types.
#[allow(
    clippy::all,
    clippy::pedantic,
    missing_docs,
    unused_qualifications,
    unreachable_pub,
    rustdoc::invalid_html_tags
)]
pub mod cln {
    tonic::include_proto!("cln");
}

pub use backend::ClnBackend;
pub use error::ClnError;
