blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: https://github.com/lightninglabs/L402sdk/issues
    about: For general questions, open a blank issue with the "question" label.
