//! Shared helpers for regtest integration tests.
//!
//! Provides environment loading, connection setup, and shared assertions
//! used across all regtest test suites.

use std::path::PathBuf;
use std::sync::Once;

use l402_core::L402Client;
use l402_core::budget::Budget;
use l402_core::cache::InMemoryTokenStore;
use l402_lnd::LndGrpcBackend;
use l402_lnd::LndRestBackend;
use l402_proto::LnBackend;
use tracing_subscriber::EnvFilter;

static INIT: Once = Once::new();

/// Initialize tracing and the TLS crypto provider (call once per test binary).
pub fn init_tracing() {
    INIT.call_once(|| {
        // Install rustls crypto provider before any TLS connections (tonic, reqwest).
        let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();

        tracing_subscriber::fmt()
            .with_env_filter(
                EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
            )
            .with_test_writer()
            .init();
    });
}

/// Load regtest environment variables from `.env.regtest`.
///
/// Searches for the env file generated by `init-regtest.sh`.
pub fn load_env() {
    let candidates = [
        PathBuf::from(".env.regtest"),
        PathBuf::from("tests/regtest/.env.regtest"),
        PathBuf::from("../../tests/regtest/.env.regtest"),
    ];

    for path in &candidates {
        if path.exists() {
            dotenvy::from_path(path).ok();
            return;
        }
    }

    tracing::warn!("No .env.regtest file found; relying on external environment variables");
}

/// Get a required environment variable or panic with a helpful message.
pub fn env_required(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| {
        panic!("Missing required env var: {key}. Run init-regtest.sh first or set it manually.")
    })
}

/// Get the L402 test server URL (Aperture proxy).
pub fn l402_server_url() -> String {
    std::env::var("L402_SERVER_URL").unwrap_or_else(|_| "http://localhost:8081".to_string())
}

/// Check if the regtest environment is available by probing the L402 server health endpoint.
///
/// Returns `true` if Aperture responds, `false` otherwise.
/// Tests use this to skip gracefully when Docker isn't running.
pub async fn regtest_available() -> bool {
    let url = format!("{}/health", l402_server_url());
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .danger_accept_invalid_certs(true)
        .build()
        .unwrap();

    match client.get(&url).send().await {
        // Aperture returns 402 for all routes (including /health) when it's running.
        // A 402 means the L402 server is up and ready.
        Ok(resp) => resp.status().is_success() || resp.status().as_u16() == 402,
        Err(_) => false,
    }
}

/// Create an `LndGrpcBackend` (Alice, payer) from regtest environment.
pub async fn lnd_grpc_backend() -> LndGrpcBackend {
    let host = env_required("LND_GRPC_HOST");
    let cert_base64 = env_required("LND_TLS_CERT_BASE64");
    let macaroon_hex = env_required("LND_MACAROON_HEX");

    // Write cert to temp file (LndGrpcBackend reads from path)
    let cert_bytes = base64_decode(&cert_base64);
    let cert_path = std::env::temp_dir().join("l402-regtest-tls.cert");
    std::fs::write(&cert_path, &cert_bytes).expect("failed to write TLS cert");

    // Write macaroon to temp file
    let macaroon_bytes = hex::decode(&macaroon_hex).expect("invalid macaroon hex");
    let macaroon_path = std::env::temp_dir().join("l402-regtest-admin.macaroon");
    std::fs::write(&macaroon_path, &macaroon_bytes).expect("failed to write macaroon");

    LndGrpcBackend::connect(
        &host,
        cert_path.to_str().unwrap(),
        macaroon_path.to_str().unwrap(),
    )
    .await
    .expect("failed to connect to LND Alice via gRPC")
}

/// Create an `LndRestBackend` (Alice, payer) from regtest environment.
pub fn lnd_rest_backend() -> LndRestBackend {
    let host =
        std::env::var("LND_REST_HOST").unwrap_or_else(|_| "https://localhost:8080".to_string());
    let macaroon_hex = env_required("LND_MACAROON_HEX");

    LndRestBackend::new(&host, &macaroon_hex).expect("failed to create LND REST backend")
}

/// Create a `ClnBackend` (payer) from regtest environment.
///
/// Returns `None` if CLN credentials are not available (CLN gRPC certs
/// are generated at runtime and may not exist).
pub async fn cln_backend() -> Option<l402_cln::ClnGrpcBackend> {
    let host =
        std::env::var("CLN_GRPC_HOST").unwrap_or_else(|_| "https://localhost:9736".to_string());

    let ca_b64 = std::env::var("CLN_CA_CERT_BASE64").ok()?;
    let client_cert_b64 = std::env::var("CLN_CLIENT_CERT_BASE64").ok()?;
    let client_key_b64 = std::env::var("CLN_CLIENT_KEY_BASE64").ok()?;

    if ca_b64.is_empty() || client_cert_b64.is_empty() || client_key_b64.is_empty() {
        tracing::warn!("CLN gRPC certs not available, skipping CLN tests");
        return None;
    }

    // Write certs to temp files
    let tmp = std::env::temp_dir();
    let ca_path = tmp.join("l402-regtest-cln-ca.pem");
    let cert_path = tmp.join("l402-regtest-cln-client.pem");
    let key_path = tmp.join("l402-regtest-cln-client-key.pem");

    std::fs::write(&ca_path, base64_decode(&ca_b64)).ok()?;
    std::fs::write(&cert_path, base64_decode(&client_cert_b64)).ok()?;
    std::fs::write(&key_path, base64_decode(&client_key_b64)).ok()?;

    match l402_cln::ClnGrpcBackend::connect(
        &host,
        ca_path.to_str().unwrap(),
        cert_path.to_str().unwrap(),
        key_path.to_str().unwrap(),
    )
    .await
    {
        Ok(backend) => Some(backend),
        Err(e) => {
            tracing::warn!("Failed to connect to CLN: {e}");
            None
        }
    }
}

/// Create a `ClnRestBackend` (payer) from regtest environment.
///
/// Returns `None` if the CLN REST rune is not available or the REST API
/// cannot be reached.
pub async fn cln_rest_backend() -> Option<l402_cln::ClnRestBackend> {
    let host =
        std::env::var("CLN_REST_URL").unwrap_or_else(|_| "https://localhost:3010".to_string());

    let rune = match std::env::var("CLN_RUNE") {
        Ok(rune) if !rune.is_empty() => rune,
        _ => {
            tracing::warn!("CLN REST rune not available, skipping CLN REST tests");
            return None;
        }
    };

    let backend = match l402_cln::ClnRestBackend::new(&host, &rune) {
        Ok(backend) => backend,
        Err(e) => {
            tracing::warn!("Failed to create CLN REST backend: {e}");
            return None;
        }
    };

    match l402_proto::LnBackend::get_info(&backend).await {
        Ok(_) => Some(backend),
        Err(e) => {
            tracing::warn!("Failed to connect to CLN REST: {e}");
            None
        }
    }
}

/// Create a `SwissKnifeBackend` from regtest environment.
///
/// Returns `None` if SwissKnife is not configured or not reachable.
pub async fn swissknife_backend() -> Option<l402_swissknife::SwissKnifeBackend> {
    let url = std::env::var("SWISSKNIFE_API_URL").ok()?;
    let api_key = std::env::var("SWISSKNIFE_API_KEY").ok()?;

    if url.is_empty() || api_key.is_empty() {
        tracing::warn!("SwissKnife credentials not available, skipping SwissKnife tests");
        return None;
    }

    let backend = l402_swissknife::SwissKnifeBackend::new(&url, &api_key);

    // Verify connectivity
    match l402_proto::LnBackend::get_info(&backend).await {
        Ok(info) => {
            tracing::info!("Connected to SwissKnife: {}", info.alias);
            Some(backend)
        }
        Err(e) => {
            tracing::warn!("Failed to connect to SwissKnife: {e}");
            None
        }
    }
}

/// Build an `L402Client` with the given backend, unlimited budget, in-memory cache.
pub fn build_l402_client<B: LnBackend + 'static>(backend: B) -> L402Client {
    L402Client::builder()
        .ln_backend(backend)
        .token_store(InMemoryTokenStore::default())
        .budget(Budget::unlimited())
        .build()
        .expect("failed to build L402Client")
}

/// Build an `L402Client` with a custom budget.
pub fn build_l402_client_with_budget<B: LnBackend + 'static>(
    backend: B,
    budget: Budget,
) -> L402Client {
    L402Client::builder()
        .ln_backend(backend)
        .token_store(InMemoryTokenStore::default())
        .budget(budget)
        .build()
        .expect("failed to build L402Client")
}

/// Build an `L402Client` with a custom token store.
pub fn build_l402_client_with_store<B, T>(backend: B, store: T) -> L402Client
where
    B: LnBackend + 'static,
    T: l402_proto::TokenStore + 'static,
{
    L402Client::builder()
        .ln_backend(backend)
        .token_store(store)
        .budget(Budget::unlimited())
        .build()
        .expect("failed to build L402Client")
}

/// Decode base64 (standard, with or without padding).
fn base64_decode(input: &str) -> Vec<u8> {
    use base64::Engine;
    use base64::engine::general_purpose::STANDARD;
    STANDARD.decode(input.trim()).expect("invalid base64")
}

/// Macro to skip a test if the regtest environment is not available.
#[macro_export]
macro_rules! skip_if_no_regtest {
    () => {
        $crate::init_tracing();
        $crate::load_env();
        if !$crate::regtest_available().await {
            eprintln!("SKIP: regtest environment not available (is Docker running?)");
            return;
        }
    };
}
