//! Full L402 protocol flow using the CLN gRPC backend as payer.
//!
//! Validates that l402-cln can pay real invoices generated by Aperture
//! (backed by lnd-bob), completing the full L402 handshake.

use regtest_helpers::*;
use serde_json::Value;
use sha2::{Digest, Sha256};

/// Skip helper for CLN-specific tests.
/// CLN certs may not always be available (e.g., if CLN image doesn't ship grpc plugin).
macro_rules! skip_if_no_cln {
    ($backend:ident) => {
        skip_if_no_regtest!();
        let $backend = match cln_backend().await {
            Some(b) => b,
            None => {
                eprintln!("SKIP: CLN backend not available (certs missing or connection failed)");
                return;
            }
        };
    };
}

#[tokio::test]
async fn full_l402_flow_cln() {
    skip_if_no_cln!(backend);

    // Verify CLN connectivity
    let info = l402_proto::LnBackend::get_info(&backend).await.unwrap();
    tracing::info!("Connected to CLN: {} ({})", info.alias, info.pubkey);
    assert!(!info.pubkey.is_empty());
    assert!(
        info.num_active_channels > 0,
        "CLN must have active channels"
    );

    let balance = l402_proto::LnBackend::get_balance(&backend).await.unwrap();
    tracing::info!("CLN balance: {} sats", balance);
    assert!(balance > 1000, "CLN must have funds to pay invoices");

    let client = build_l402_client(backend);

    let url = format!("{}/api/data", l402_server_url());
    let response = client.get(&url).await.unwrap();

    assert_eq!(response.status().as_u16(), 200);
    assert!(response.paid());
    assert!(!response.cached_token());

    let receipt = response.receipt().unwrap();
    assert_eq!(receipt.amount_sats, 100);
    assert_eq!(receipt.response_status, 200);
    assert!(!receipt.payment_hash.is_empty());
    assert!(!receipt.preimage.is_empty());

    let body: Value = response.json().await.unwrap();
    assert_eq!(body["ok"], true);
    assert_eq!(body["resource"], "data");
}

#[tokio::test]
async fn cln_premium_endpoint() {
    skip_if_no_cln!(backend);

    let client = build_l402_client(backend);

    let url = format!("{}/api/premium", l402_server_url());
    let response = client.get(&url).await.unwrap();

    assert_eq!(response.status().as_u16(), 200);
    assert!(response.paid());

    let receipt = response.receipt().unwrap();
    assert_eq!(receipt.amount_sats, 500);

    let body: Value = response.json().await.unwrap();
    assert_eq!(body["resource"], "premium");
}

#[tokio::test]
async fn cln_receipt_preimage_matches_hash() {
    skip_if_no_cln!(backend);

    let client = build_l402_client(backend);

    let url = format!("{}/api/cheap", l402_server_url());
    let response = client.get(&url).await.unwrap();

    assert_eq!(response.status().as_u16(), 200);
    let receipt = response.receipt().unwrap();

    let preimage_bytes = hex::decode(&receipt.preimage).unwrap();
    let computed_hash = hex::encode(Sha256::digest(&preimage_bytes));
    assert_eq!(computed_hash, receipt.payment_hash);

    assert_eq!(receipt.amount_sats, 10);
}

#[tokio::test]
async fn cln_token_caching() {
    skip_if_no_cln!(backend);

    let client = build_l402_client(backend);

    let url = format!("{}/api/data", l402_server_url());

    // First request pays
    let resp1 = client.get(&url).await.unwrap();
    assert!(resp1.paid());
    let _ = resp1.text().await.unwrap();

    // Second request uses cache
    let resp2 = client.get(&url).await.unwrap();
    assert!(!resp2.paid());
    assert!(resp2.cached_token());
}
