//! Full L402 protocol flow using the SwissKnife backend.
//!
//! SwissKnife is a custodial wallet connected to lnd-bob. These tests verify
//! that l402-swissknife can pay invoices generated by Aperture and complete
//! the full L402 handshake.

use regtest_helpers::*;
use serde_json::Value;

macro_rules! skip_if_no_swissknife {
    ($backend:ident) => {
        skip_if_no_regtest!();
        let $backend = match swissknife_backend().await {
            Some(b) => b,
            None => {
                eprintln!("SKIP: SwissKnife not available");
                return;
            }
        };
    };
}

#[tokio::test]
async fn full_l402_flow_swissknife() {
    skip_if_no_swissknife!(backend);

    // Verify connectivity
    let info = l402_proto::LnBackend::get_info(&backend).await.unwrap();
    tracing::info!("Connected to SwissKnife: {}", info.alias);

    let balance = l402_proto::LnBackend::get_balance(&backend).await.unwrap();
    tracing::info!("SwissKnife balance: {} sats", balance);

    let client = build_l402_client(backend);

    let url = format!("{}/api/data", l402_server_url());
    let response = client.get(&url).await.unwrap();

    assert_eq!(response.status().as_u16(), 200);
    assert!(response.paid());
    assert!(!response.cached_token());

    let receipt = response.receipt().unwrap();
    assert_eq!(receipt.amount_sats, 100);
    assert_eq!(receipt.response_status, 200);
    assert!(!receipt.payment_hash.is_empty());
    assert!(!receipt.preimage.is_empty());

    let body: Value = response.json().await.unwrap();
    assert_eq!(body["ok"], true);
    assert_eq!(body["resource"], "data");
}

#[tokio::test]
async fn swissknife_token_caching() {
    skip_if_no_swissknife!(backend);

    let client = build_l402_client(backend);
    let url = format!("{}/api/cheap", l402_server_url());

    // First request pays
    let resp1 = client.get(&url).await.unwrap();
    assert!(resp1.paid());
    let _ = resp1.text().await.unwrap();

    // Second request uses cache
    let resp2 = client.get(&url).await.unwrap();
    assert!(!resp2.paid());
    assert!(resp2.cached_token());
}

#[tokio::test]
async fn swissknife_nonexistent_endpoint() {
    skip_if_no_swissknife!(backend);

    let client = build_l402_client(backend);
    let url = format!("{}/api/nonexistent", l402_server_url());
    let response = client.get(&url).await.unwrap();

    assert_eq!(response.status().as_u16(), 404);
    assert!(!response.paid());
}
