//! CLN gRPC backend implementation using vendored protos.
//!
//! Connects to a Core Lightning node via gRPC with mutual TLS (mTLS)
//! authentication. Uses the `Pay` RPC for invoice payments, `ListFunds`
//! for balance queries, and `Getinfo` for node information.
//!
//! # Example
//!
//! ```rust,no_run
//! use l402_cln::ClnGrpcBackend;
//!
//! # async fn example() {
//! let backend = ClnGrpcBackend::connect(
//!     "https://localhost:9736",
//!     "/path/to/ca.pem",
//!     "/path/to/client.pem",
//!     "/path/to/client-key.pem",
//! ).await.unwrap();
//! // Use with L402Client::builder().ln_backend(backend)...
//! # }
//! ```

use std::fmt;

use async_trait::async_trait;
use l402_proto::ClientError;
use l402_proto::{LnBackend, NodeInfo, PaymentResult};
use tonic::transport::{Certificate, Channel, ClientTlsConfig, Identity};
use tracing::debug;

use crate::cln;
use crate::cln::node_client::NodeClient;
use crate::error::ClnError;

/// Core Lightning (CLN) Lightning backend via gRPC.
///
/// Connects to a CLN node using mutual TLS (mTLS) authentication,
/// then implements the [`LnBackend`] trait for invoice payments.
/// Uses CLN's high-level `Pay` RPC for pathfinding and payment execution.
///
/// # Authentication
///
/// CLN's gRPC interface requires mTLS. You need three files:
/// - **CA certificate** (`ca.pem`): verifies the server identity
/// - **Client certificate** (`client.pem`): authenticates this client
/// - **Client key** (`client-key.pem`): private key for the client cert
///
/// These files are generated by CLN in `~/.lightning/<network>/`.
///
/// # Example
///
/// ```rust,no_run
/// use l402_cln::ClnGrpcBackend;
/// use l402_proto::LnBackend;
///
/// # async fn example() {
/// let backend = ClnGrpcBackend::connect(
///     "https://localhost:9736",
///     "/path/to/ca.pem",
///     "/path/to/client.pem",
///     "/path/to/client-key.pem",
/// ).await.unwrap();
///
/// let info = backend.get_info().await.unwrap();
/// println!("Connected to: {} ({})", info.alias, info.pubkey);
/// # }
/// ```
pub struct ClnGrpcBackend {
    client: NodeClient<Channel>,
    address: String,
}

impl fmt::Debug for ClnGrpcBackend {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ClnGrpcBackend")
            .field("address", &self.address)
            .finish_non_exhaustive()
    }
}

impl ClnGrpcBackend {
    /// Connect to a CLN node using mTLS authentication.
    ///
    /// # Arguments
    ///
    /// * `address` - gRPC endpoint (e.g. `https://localhost:9736`)
    /// * `ca_cert_path` - Path to the CA certificate (`ca.pem`)
    /// * `client_cert_path` - Path to the client certificate (`client.pem`)
    /// * `client_key_path` - Path to the client private key (`client-key.pem`)
    ///
    /// # Errors
    ///
    /// Returns [`ClnError::Io`] if certificate files cannot be read,
    /// or [`ClnError::Transport`] if the gRPC connection fails.
    pub async fn connect(
        address: &str,
        ca_cert_path: &str,
        client_cert_path: &str,
        client_key_path: &str,
    ) -> Result<Self, ClnError> {
        debug!(address = %address, "connecting to CLN node via gRPC");

        // Read TLS certificates and key
        let ca_cert = tokio::fs::read(ca_cert_path).await?;
        let client_cert = tokio::fs::read(client_cert_path).await?;
        let client_key = tokio::fs::read(client_key_path).await?;

        let tls_config = ClientTlsConfig::new()
            .ca_certificate(Certificate::from_pem(ca_cert))
            .identity(Identity::from_pem(client_cert, client_key))
            .domain_name("localhost");

        let channel = Channel::from_shared(address.to_string())
            .map_err(|e| ClnError::Payment(format!("invalid address: {e}")))?
            .tls_config(tls_config)?
            .connect()
            .await?;

        let client = NodeClient::new(channel);

        Ok(Self {
            client,
            address: address.to_string(),
        })
    }

    /// Connect using environment variables.
    ///
    /// Reads from:
    /// - `CLN_GRPC_HOST` (default: `https://localhost:9736`)
    /// - `CLN_CA_CERT_PATH` (default: `~/.lightning/bitcoin/ca.pem`)
    /// - `CLN_CLIENT_CERT_PATH` (default: `~/.lightning/bitcoin/client.pem`)
    /// - `CLN_CLIENT_KEY_PATH` (default: `~/.lightning/bitcoin/client-key.pem`)
    ///
    /// # Errors
    ///
    /// Returns an error if certificate files cannot be read or the connection fails.
    pub async fn from_env() -> Result<Self, ClnError> {
        let host =
            std::env::var("CLN_GRPC_HOST").unwrap_or_else(|_| "https://localhost:9736".to_string());
        let ca_cert = std::env::var("CLN_CA_CERT_PATH")
            .unwrap_or_else(|_| expand_home("~/.lightning/bitcoin/ca.pem"));
        let client_cert = std::env::var("CLN_CLIENT_CERT_PATH")
            .unwrap_or_else(|_| expand_home("~/.lightning/bitcoin/client.pem"));
        let client_key = std::env::var("CLN_CLIENT_KEY_PATH")
            .unwrap_or_else(|_| expand_home("~/.lightning/bitcoin/client-key.pem"));

        Self::connect(&host, &ca_cert, &client_cert, &client_key).await
    }
}

#[async_trait]
impl LnBackend for ClnGrpcBackend {
    async fn pay_invoice(
        &self,
        bolt11: &str,
        max_fee_sats: u64,
    ) -> Result<PaymentResult, ClientError> {
        debug!(invoice = %&bolt11[..bolt11.len().min(20)], "paying invoice via CLN");

        // Convert max_fee_sats to millisatoshis for CLN's maxfee field.
        let max_fee_msat = max_fee_sats.saturating_mul(1000);

        let request = cln::PayRequest {
            bolt11: bolt11.to_string(),
            maxfee: Some(cln::Amount { msat: max_fee_msat }),
            retry_for: Some(60),
            ..Default::default()
        };

        let response = self
            .client
            .clone()
            .pay(request)
            .await
            .map_err(ClnError::from)?
            .into_inner();

        match response.status() {
            cln::pay_response::PayStatus::Complete => {
                let preimage = hex::encode(&response.payment_preimage);
                let payment_hash = hex::encode(&response.payment_hash);

                // CLN returns amounts in millisatoshis via the Amount message.
                let amount_msat = response.amount_msat.as_ref().map_or(0, |a| a.msat);
                let sent_msat = response.amount_sent_msat.as_ref().map_or(0, |a| a.msat);
                let fee_msat = sent_msat.saturating_sub(amount_msat);

                Ok(PaymentResult {
                    preimage,
                    payment_hash,
                    amount_sats: amount_msat / 1000,
                    fee_sats: fee_msat / 1000,
                })
            }
            cln::pay_response::PayStatus::Pending => {
                Err(ClnError::Payment("payment still pending".to_string()).into())
            }
            cln::pay_response::PayStatus::Failed => {
                Err(ClnError::Payment("payment failed".to_string()).into())
            }
        }
    }

    async fn get_balance(&self) -> Result<u64, ClientError> {
        debug!("querying balance via CLN ListFunds");

        let response = self
            .client
            .clone()
            .list_funds(cln::ListfundsRequest { spent: None })
            .await
            .map_err(ClnError::from)?
            .into_inner();

        // Sum our_amount_msat across all channels to get spendable balance.
        let total_msat: u64 = response
            .channels
            .iter()
            .map(|ch| ch.our_amount_msat.as_ref().map_or(0, |a| a.msat))
            .sum();

        Ok(total_msat / 1000)
    }

    async fn get_info(&self) -> Result<NodeInfo, ClientError> {
        debug!("querying node info via CLN Getinfo");

        let response = self
            .client
            .clone()
            .getinfo(cln::GetinfoRequest {})
            .await
            .map_err(ClnError::from)?
            .into_inner();

        let pubkey = hex::encode(&response.id);
        let alias = if response.alias.is_empty() {
            "CLN Node".to_string()
        } else {
            response.alias
        };

        Ok(NodeInfo {
            pubkey,
            alias,
            num_active_channels: response.num_active_channels,
        })
    }
}

/// Expand `~` to the home directory.
fn expand_home(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return format!("{home}/{rest}");
        }
    }
    path.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_display() {
        let err = ClnError::Payment("no route found".to_string());
        assert_eq!(err.to_string(), "payment failed: no route found");
    }

    #[test]
    fn error_conversion() {
        let cln_err = ClnError::Payment("timeout".to_string());
        let client_err: ClientError = cln_err.into();
        match client_err {
            ClientError::PaymentFailed { reason } => assert_eq!(reason, "timeout"),
            _ => panic!("expected PaymentFailed"),
        }
    }

    #[test]
    fn expand_home_tilde() {
        // SAFETY: test runs single-threaded; set_var is safe here.
        unsafe { std::env::set_var("HOME", "/home/test") };
        assert_eq!(
            expand_home("~/.lightning/bitcoin/ca.pem"),
            "/home/test/.lightning/bitcoin/ca.pem"
        );
        assert_eq!(expand_home("/absolute/path"), "/absolute/path");
    }

    #[test]
    fn debug_format() {
        // Verify debug output includes address but not sensitive data.
        let display = "ClnGrpcBackend { address: \"https://localhost:9736\", .. }".to_string();
        assert!(display.contains("localhost:9736"));
    }
}
